name: bonfire
description: "A modern take on the Discord Client"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  firebridge:
    path: /Users/eric/Documents/development/languages/dart/nyxx

  markdown_viewer:
    path: packages/markdown_viewer

  # firebridge_extensions:
  #   path: packages/firebridge_extensions

  google_fonts: ^6.2.1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  flutter_keyboard_size: ^1.0.1
  freezed_annotation: ^3.1.0
  json_serializable: ^6.7.1

  go_router: ^17.0.0
  flutter_prism: ^0.2.2

  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./libs/universal/media_kit_libs_video

  video_player_media_kit:
    git: 
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: video_player_media_kit

  url_launcher: ^6.2.6
  sticky_headers: ^0.3.0
  flutter_svg: ^2.2.3
  collection: ^1.18.0
  http: ^1.2.1
  audioplayers: ^6.0.0
  file_icon: ^1.0.0
  internet_file: ^1.2.0
  file_selector: ^1.1.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.3
  universal_platform: ^1.1.0
  loading_animation_widget: ^1.2.1
  hive_ce: ^2.16.0
  universal_io: ^2.3.1

  flutter_thumbhash: ^0.1.0
  flutter_cache_manager: ^3.4.0
  file_picker: ^10.3.8
  path: ^1.9.0
  flutter_localization: ^0.3.3
  # flutter_webrtc: ^0.12.11
  crypto: ^3.0.6
  shimmer: ^3.0.0
  rubber: ^1.1.0
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  flutter_local_notifications: ^19.5.0
  flutter_webrtc: ^1.2.1
  sdp_transform: ^0.3.2
  webcrypto: ^0.6.0
  web_socket_channel: ^3.0.2
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1
  webview_flutter: ^4.10.0
  dart_mappable: ^4.6.1
  go_transitions: ^0.8.3

dependency_overrides:
  firebridge:
    path: ./packages/firebridge

  http: ^1.2.1

  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./libs/universal/media_kit_libs_video

  video_player_media_kit:
    git: 
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: video_player_media_kit

  flutter_keyboard_visibility_web:
    git:
      url: https://github.com/raldhafiri/flutter_keyboard_visibility.git
      ref: master
      path: flutter_keyboard_visibility_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.4
  dart_mappable_builder: ^4.6.3

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/sdps/
