name: bonfire
description: "A modern take on the Discord Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fireview:
    git:
      url: https://github.com/OpenBonfire/fireview.git
      ref: a537dad4fa77e0ef99bc69c6bb1eeb6bb0aa65e5

  firebridge:
    git:
      url: https://github.com/OpenBonfire/firebridge
      ref: 0d8690414342fc5728dd6f4cd270febf3d5924cc

  markdown_viewer:
    git:
      url: https://github.com/OpenBonfire/markdown_viewer
      ref: 4d3e47209a5652cd81736aa3838c68979a796e81

  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  get_storage: ^2.1.1
  signals: ^5.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_keyboard_size: ^1.0.1
  relative_time: ^5.0.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  go_router: ^13.2.4
  flutter_background_service: ^5.0.5
  flutter_prism: ^0.2.2
  
  video_player_media_kit: ^1.0.5
  media_kit_libs_android_video: any
  media_kit_libs_ios_video: any
  media_kit_libs_macos_video: any
  media_kit_libs_windows_video: any
  media_kit_libs_linux: any
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.2.6
  sticky_headers: ^0.3.0+2
  # firebridge: ^6.2.12
  firebridge_extensions: ^4.1.2
  flutter_svg: ^2.0.10+1
  flutter_vlc_player: ^7.4.2
  bitsdojo_window: ^0.1.6
  collection: ^1.18.0
  http: ^1.2.1
  logger: ^2.3.0
  audioplayers: ^6.0.0
  file_icon: ^1.0.0
  internet_file: ^1.2.0
  file_selector: ^1.0.3
  dio: ^5.4.3+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  universal_platform: ^1.1.0
  dynamic_height_grid_view: ^0.0.4

dependency_overrides:
  webview_flutter_platform_interface: ^2.4.0
  http: ^1.2.1

  firebridge:
    git:
      url: https://github.com/OpenBonfire/firebridge
      ref: 687149c3f6d4acf32d20a655511e2f06ff3f7d3a

  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
      ref: main
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
      ref: main
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
      ref: main

  media_kit_native_event_loop:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_native_event_loop
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/