name: firebridge
version: 6.2.14
description: An experimental package to use the Discord bot API with user accounts, built off of Nyxx.
homepage: https://github.com/OpenBonfire/firebridge
repository: https://github.com/OpenBonfire/firebridge
documentation: https://nyxx.l7ssha.xyz
issue_tracker: https://github.com/OpenBonfire/firebridge/issues
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.2.2
  logging: ^1.0.1
  path: ^1.8.3
  retry: ^3.1.0
  eterl: ^1.0.1
  runtime_type: ^1.0.1
  meta: ^1.15.0
  oauth2: ^2.0.2
  archive: ^3.6.1
  universal_io: ^2.2.2
  web_socket_channel: ^3.0.1
  stream_channel: ^2.1.2
  websocket_universal: ^1.2.5
  combine: ^0.5.8

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
  nock: ^1.2.1
  mocktail: ^1.0.0
  matcher: ^0.12.16
