name: markdown_viewer
description: A Markdown renderer for Flutter. Render Markdown String to rich
  text output.
version: 0.6.2
repository: https://github.com/tagnote-app/markdown_viewer

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  dart_markdown: ^3.1.7
  firebridge:
    path: ../firebridge
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.15
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
